openapi: 3.0.0
info:
    title: Identifier Generator
    version: 0.1.0
paths:
    /generate:
        get:
            summary: Generates identifiers based on selected method
            parameters:
                - name: count
                  in: query
                  required: false
                  schema:
                      type: integer
                      minimum: 1
                      maximum: 100
                      default: 1
                - name: generator
                  in: query
                  required: false
                  schema:
                      default: 'standard'
                      $ref: '#/components/schemas/GeneratorType'
            responses:
                "200":
                    description: Generated identifiers and information
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GeneratedIdentifiers'
                default:
                    description: Unexpected error
components:
    schemas:
        GeneratedIdentifiers:
            type: object
            properties:
                info:
                    type: object
                    properties:
                        generator:
                            $ref: '#/components/schemas/GeneratorType'
                values:
                    type: array
                    items:
                        type: string
        GeneratorType:
            type: string
            enum: ["standard", "guid", "uuid"]
